### PR TITLE
Fix html-proofer failures

### LINKED ISSUE #464: HTML-Proofer found 2 failures
```bash
- ./_site/screenshots.html
  *  External link https://github.com/flyve-mdm/flyve-mdm-android-agent/compare/v0.99.45...v2.0.0 failed: 404 No error
  *  External link https://github.com/flyve-mdm/flyve-mdm-android/compare/v0.99.45...v0.99.46 failed: 404 No error
htmlproofer 3.7.2 | Error:  HTML-Proofer found 2 failures!
```

### PR DESCRIPTION
**Pull request by Naylin15**
### Changes description
Improve CI command to update the development folder and not only rewrite new files

### Checklist

Please check if your PR fulfills the following specifications:

- [ ] Tests for the changes have been added
- [x] Docs have been added/updated

### Estimated time

|Assignee|:tomato:|
|:---|:---:|
|@Naylin15 |4|

### References

Closes #464
Related #N/A
Depends on #N/A

### CODE REVIEW

File: ci/scripts/ci_generate_documentation.sh [hunk 1]
```diff
@@ -65,7 +65,7 @@ mv ./development/code-documentation/overview-summary.html ./development/code-doc
 grep -rl overview-summary.html development/code-documentation/ | xargs sed -i 's|overview-summary.html|index.html|g'
 
 # send development folder to project site with the documentation updated
-yarn gh-pages --dist ./development/ --dest ./development/ --add -m "docs(development): update documentation
+yarn gh-pages --dist ./development/ --dest ./development/ -m "docs(development): update documentation
```
Comment (ajsb85) [inline ci/scripts/ci_generate_documentation.sh]: @Naylin15 missed symbol at the end '"'

Comment (Naylin15) [reply ci/scripts/ci_generate_documentation.sh]: Hi, @ajsb85 

I create that commit with a body, specifying the folders updated

The closing symbols are at a line [71](https://git.io/fQVeS)
